< ../config.mk

all:VQ:
	bin/targets | xargs mk

results/%.tsv: data/%/*.tsv
	set -x
	mkdir -p `dirname $target`
	awk 'FNR==1 && NR!=1{next;}{print}' $prereq > $target.build \
	&& mv $target.build $target
