< ../config.mk

all:VQ:
	bin/targets | xargs mk

results/%.snp.tsv: data/%.txt
	mkdir -p `dirname $target`
	echo "PMID	SNP" > $target.build
	PMID=$(ls -1 $prereq | cut -d "/" -f3 | cut -d. -f1)
	SNP=$(cat $prereq | tr " " "_" | sed -e "s#,#_,#g" -e "s#;#_,#g" -e "s#^#_#g" -e "s#_(#,_#g" -e "s#)#\n#g" | grep "_rs[1-9].*_" | sed "s/rs/\n/g" \
	| sed -n 's/^\([0-9]*\).*/\1/p' | sed "s/^[0-9]/rs/g" | tr "\n" "," | tr -s "," | sed "s#^,##g" | sed "s#,\$##g")
	if [ "$SNP" = "" ]; then 
		SNP="NA"
	fi
	echo "$PMID	$SNP" >> $target.build \
	&& mv $target.build $target
